---
app:
  width: 972
  height: 648
directories:
  icon: "assets/icon.ico"
  lang: "lang"
  exportlogname: "bin/latest.log"
  exportstats: "bin/statistics.txt"
  exportchart: "bin/latest.png"
  gen: "generated/generated.csv"
  geninfo: "generated/generated.txt"
  exporteval: "bin/eval.txt"